name: Deploy Infrastructure in Azure

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ infrastructure ]

defaults:
  run:
    working-directory: ./terraform/infrastructure

jobs:

  Terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false
        
      - name: Terraform Apply
        run: terraform apply --auto-approve -lock=false
  
  Helm:
    runs-on: ubuntu-latest
    needs: Terraform
    steps:

      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}
          # Resource Group Name
          resource-group: rg-retro_pacman
          # AKS Cluster Name
          cluster-name:  kc_retro_pacman
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace pacman \
            retropacmanapp \
            ./helm/ 